BusinessMQ.Web/Areas/Message/Controllers/MessageController.cs
using BusinessMQ.Domain;
using BusinessMQ.Domain.Dal;
using BusinessMQ.Domain.Model;
using BusinessMQ.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BSF.Db;
using BSF.BaseService.BusinessMQ.SystemRuntime;
using System.Globalization;
using Webdiyer.WebControls.Mvc;

namespace BusinessMQ.Web.Areas.Message.Controllers
{
    public class MessageController : BaseController
    {
        //
        // GET: /Message/Message/

        private tb_datanode_dal nodeDal = new tb_datanode_dal();

        public ActionResult Index(string node = "", string tablepartition = "", string daypartition = "", string mqid= "",bool isclick=false, int pageIndex = 1, int pageSize = 30)
        {
            ViewBag.mqid = mqid;
            ViewBag.node = node;
            ViewBag.tablepartition = tablepartition; ViewBag.daypartition = daypartition; ViewBag.isclick = isclick;
            int count = 0;
            IList<tb_messagequeue_model> list = new List<tb_messagequeue_model>();
            PagedList<tb_messagequeue_model> pageList = new PagedList<tb_messagequeue_model>(list, pageIndex, pageSize, count);
            if (!string.IsNullOrWhiteSpace(node))
            {
                
                using (DbConn conn = DbConn.CreateConn(DataConfig.DataNodeParConn(node)))
                {
                    conn.Open();
                    string tablename = PartitionRuleHelper.GetTableName(Convert.ToInt32(tablepartition), DateTime.ParseExact(daypartition, "yyMMdd", CultureInfo.InvariantCulture));
                    tb_messagequeue_dal dal = new tb_messagequeue_dal(); dal.TableName = tablename;
                    list = dal.GetPageList(conn, pageIndex, pageSize, mqid, ref count);
                    pageList = new PagedList<tb_messagequeue_model>(list, pageIndex, pageSize, count);
                }
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("List", pageList);
            }
            return View(pageList);
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(tb_messagequeue_model model, string node, string tablepartition,string daypartition)
        {
            DateTime serverdate = DateTime.Now;
            using (DbConn conn = DbConn.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                serverdate = conn.GetServerDate();
            }
            using (DbConn conn = DbConn.CreateConn(DataConfig.DataNodeParConn(node)))
            {
                conn.Open();
                model.sqlcreatetime = serverdate;
                model.mqcreatetime = DateTime.Now;
                string tablename = PartitionRuleHelper.GetTableName(Convert.ToInt32(tablepartition), DateTime.ParseExact(daypartition, "yyMMdd", CultureInfo.InvariantCulture));
                var dal =  new tb_messagequeue_dal();dal.TableName=tablename;
                if (dal.Add(conn, tablename, model))
                {
                    return RedirectToAction("index");
                }
                else
                {
                    ModelState.AddModelError("Error", "更新错误");
                    return View(model);
                }
            }
        }
        [HttpPost]
        public ActionResult Delete(long id, string node)
        {
            using (DbConn conn = DbConn.CreateConn(DataConfig.DataNodeParConn(node)))
            {
                conn.Open();
                var mqidinfo = BSF.BaseService.BusinessMQ.SystemRuntime.PartitionRuleHelper.GetMQIDInfo(Convert.ToInt64(id));
                string tablename = PartitionRuleHelper.GetTableName(mqidinfo.TablePartition, mqidinfo.Day);
                var dal = new tb_messagequeue_dal(); dal.TableName = tablename;
                if (dal.SetState(conn,id,(byte)BSF.BaseService.BusinessMQ.SystemRuntime.EnumMessageState.Deleted))
                {
                    return Json(new { code = 1, msg = "删除成功" });
                }
                return Json(new { code = -1, msg = "删除失败" });
            }
        }
        public ActionResult Update(long id, string node)
        {
            using (DbConn conn = DbConn.CreateConn(DataConfig.DataNodeParConn(node)))
            {
                conn.Open();
                ViewBag.node = node;
                var mqidinfo = BSF.BaseService.BusinessMQ.SystemRuntime.PartitionRuleHelper.GetMQIDInfo(Convert.ToInt64(id));
                ViewBag.tablepartition = mqidinfo.TablePartition; ViewBag.daypartition = mqidinfo.Day.ToString("yyMMdd");
                string tablename = PartitionRuleHelper.GetTableName(mqidinfo.TablePartition, mqidinfo.Day);
                var dal = new tb_messagequeue_dal(); dal.TableName = tablename;
                tb_messagequeue_model model = dal.GetModel(conn, id, tablename);
                return View(model);
            }
        }
        [HttpPost]
        public ActionResult Update(tb_messagequeue_model model, string node, long id)
        {
            ViewBag.node = node;
            var mqidinfo = BSF.BaseService.BusinessMQ.SystemRuntime.PartitionRuleHelper.GetMQIDInfo(Convert.ToInt64(id));
            ViewBag.tablepartition = mqidinfo.TablePartition; ViewBag.daypartition = mqidinfo.Day.ToString("yyMMdd");
            string tablename = PartitionRuleHelper.GetTableName(mqidinfo.TablePartition, mqidinfo.Day);
            var dal = new tb_messagequeue_dal(); dal.TableName = tablename;
            using (DbConn conn = DbConn.CreateConn(DataConfig.DataNodeParConn(node)))
            {
                conn.Open();
                tb_messagequeue_model result = dal.GetModel(conn, id, tablename);
                if (result != null)
                {
                    result.message = model.message;
                    result.state = model.state;
                    result.source = model.source;
                    if (dal.Update(conn, result, tablename))
                    {
                        return RedirectToAction("Index", new { node =node, tablepartition = BSF.BaseService.BusinessMQ.SystemRuntime.PartitionRuleHelper.PartitionNameRule( mqidinfo.TablePartition), daypartition = mqidinfo.Day.ToString("yyMMdd"), mqid = id });
                    }
                }
                ModelState.AddModelError("Error", "更新错误");
                return View(result);
            }
        }
        public JsonResult GetNodeList()
        {
            IList<string> array = new List<string>();
            using (DbConn conn = DbConn.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                array = nodeDal.GetNodeList(conn);
                if (array != null && array.Count > 0)
                {
                    return Json(array, JsonRequestBehavior.AllowGet);
                }
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult GetPartitionList(string node)
        {
            try
            {

                using (DbConn conn = DbConn.CreateConn(DataConfig.DataNodeParConn(node)))
                {
                    conn.Open();
                    var array = new tb_messagequeue_dal().GetTablePartitions(conn).Select(c => BSF.BaseService.BusinessMQ.SystemRuntime.PartitionRuleHelper.PartitionNameRule(c)).ToList();
                    if (array != null && array.Count > 0)
                    {
                        return Json(array, JsonRequestBehavior.AllowGet);
                    }
                    return Json("", JsonRequestBehavior.AllowGet);
                }
                
            }
            catch (Exception ex)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult GetDayList(string node, string tablepartition)
        {
            try
            {
                string mqpath = "";
                using (DbConn conn = DbConn.CreateConn(DataConfig.MqManage))
                {
                    conn.Open();
                    tb_mqpath_dal mqpathdal = new tb_mqpath_dal();
                    var model = mqpathdal.GetByPartitionID(conn, PartitionRuleHelper.GetPartitionID(new PartitionIDInfo() { DataNodePartition = Convert.ToInt32(node), TablePartition = Convert.ToInt32(tablepartition) }));
                    if(model!=null)
                        mqpath = model.mqpath;
                }
                using (DbConn conn = DbConn.CreateConn(DataConfig.DataNodeParConn(node)))
                {
                    conn.Open();
                    var array = new tb_messagequeue_dal().GetDayPartitions(conn, Convert.ToInt32(tablepartition)).Select(c => c.ToString("yyMMdd")).ToList();
                    if (array != null && array.Count > 0)
                    {
                        return Json(new { array, mqpath }, JsonRequestBehavior.AllowGet);
                    }
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult GetMQInfo(string mqid)
        {
            try
            {
                var info = BSF.BaseService.BusinessMQ.SystemRuntime.PartitionRuleHelper.GetMQIDInfo(Convert.ToInt64(mqid));
                return Json(new { DataNodePartition=BSF.BaseService.BusinessMQ.SystemRuntime.PartitionRuleHelper.PartitionNameRule(info.DataNodePartition), TablePartition=BSF.BaseService.BusinessMQ.SystemRuntime.PartitionRuleHelper.PartitionNameRule(info.TablePartition), day = info.Day.ToString("yyMMdd") }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        } 
        
    }
}

BusinessMQ.Web/Areas/ProConsum/Controllers/ConsumerController.cs
using BusinessMQ.Domain;
using BusinessMQ.Domain.Dal;
using BusinessMQ.Domain.Model.manage;
using BusinessMQ.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BSF.Db;
using BusinessMQ.Domain.Model;
using Webdiyer.WebControls.Mvc;

namespace BusinessMQ.Web.Areas.ProConsum.Controllers
{
    public class ConsumerController : BaseController
    {
        //
        // GET: /ProConsum/Consumer/

        private tb_consumer_dal dal = new tb_consumer_dal();
        public ActionResult Index(string partitionid, string consumerclientid, string mqpathid, int pageIndex = 1, int pageSize = 30)
        {
            ViewBag.partitionid = partitionid; ViewBag.consumerclientid = consumerclientid; ViewBag.mqpathid = mqpathid;
            using (DbConn conn = DbConn.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                ViewBag.ServerDate = conn.GetServerDate();
                int count = 0;
                var list = dal.GetPageList2(conn, partitionid, consumerclientid, mqpathid, pageIndex, pageSize, ref count);
                PagedList<RegisterdConsumersModel> pageList = new PagedList<RegisterdConsumersModel>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("List", pageList);
                }

                return View(pageList);
            }
        }
        [HttpPost]
        public ActionResult Delete(int id, int mqpathid)
        {
            try
            {
                using (DbConn conn = DbConn.CreateConn(DataConfig.MqManage))
                {
                    try
                    {
                        conn.Open();
                        conn.BeginTransaction();

                        var item = new tb_consumer_partition_dal().Get(conn, id);
                        new tb_consumer_dal().DeleteNotOnLineByClientID(conn, item.consumerclientid, 20);
                        var consumer = new tb_consumer_dal().GetByTempId(conn, item.lastconsumertempid);
                        if (consumer != null && consumer.tempid == 0)
                        {
                            throw new Exception("当前消费者未处于正常离线状态,若是非正常断线状态,可以在20s超时后尝试");
                        }
                        new tb_consumer_partition_dal().Delete(conn, id);
                        conn.Commit();

                    }
                    catch (Exception exp)
                    {
                        conn.Rollback();
                        throw exp;
                    }
                }
                this.SendCommandToRedistReStart(mqpathid, BSF.BaseService.BusinessMQ.SystemRuntime.EnumCommandReceiver.Consumer);
                return Json(new { code = 1, msg = "删除成功" });
            }

            catch (Exception e)
            {
                return Json(new { code = -1, msg = e.Message });
            }

        }
        [HttpPost]
        public ActionResult ClearNotOnLineByClientID(int id, int mqpathid)
        {
            try
            {
                using (DbConn conn = DbConn.CreateConn(DataConfig.MqManage))
                {
                    try
                    {
                        conn.Open();
                        conn.BeginTransaction();
                        var item = new tb_consumer_partition_dal().Get(conn, id);
                        new tb_consumer_dal().DeleteNotOnLineByClientID(conn, item.consumerclientid, 20);

                        conn.Commit();

                    }
                    catch (Exception exp)
                    {
                        conn.Rollback();
                        throw exp;
                    }

                    return Json(new { code = 1, msg = "清理完毕" });
                }
            }
            catch (Exception e)
            {
                return Json(new { code = -1, msg = e.Message });
            }

        }
        public ActionResult UpdateLastMqID(int id, string mqpathid)
        {
            using (DbConn conn = DbConn.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                var o = new tb_consumer_partition_dal().Get(conn, id);
                ViewBag.id = id;
                ViewBag.lastmqid = o.lastmqid; ViewBag.mqpathid = mqpathid;

            }
            return View();

        }
        [HttpPost]
        public ActionResult SaveUpdateLastMqID(int id, long lastmqid, int mqpathid)
        {
            using (DbConn conn = DbConn.CreateConn(DataConfig.MqManage))
            {
                conn.Open();
                try
                {
                    if (new tb_consumer_partition_dal().UpdateLastMqIdByPartitionId(conn, id, lastmqid) > 0)
                    {
                        this.SendCommandToRedistReStart(mqpathid, BSF.BaseService.BusinessMQ.SystemRuntime.EnumCommandReceiver.Consumer);
                        return RedirectToAction("index");
                    }
                    else
                    {
                        ModelState.AddModelError("Error", "更新失败");
                        return View();
                    }
                }
                catch (Exception exp)
                {
                    ModelState.AddModelError("Error", exp.Message);
                    return View();
                }
            }
        }
    }
}

BusinessMQ.Web/Areas/ProConsum/Views/Consumer/Add.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
</head>
<body>
    <div>
        
    </div>
</body>
</html>

BusinessMQ.Web/Areas/ProConsum/Views/Consumer/Index.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<BusinessMQ.Domain.Model.RegisterdConsumersModel>
@{
    ViewBag.Title = "消费者管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    function Delete(id, mqpathid) {
        if (confirm("确定删除,删除后该分区的消费信息无法恢复？")) {
            $.ajax({
                url: '@Url.Action("Delete","Consumer")',
                type: "post",
                data: {
                    id: id,
                    mqpathid: mqpathid
                },
                success: function (data) {
                    if (data.code > 0) {
                        alert("成功！");
                        window.location = window.location;
                    }
                    else {
                        alert(data.msg);
                    }
                }
            })
        }
    }
    function ClearNotOnLineByClientID(id,mqpathid) {
        if (confirm("确认当前异常中断的客户端已离线吗,重置后若该客户端依然在线,则该客户端心跳异常？")) {
            $.ajax({
                url: '@Url.Action("ClearNotOnLineByClientID","Consumer")',
                type: "post",
                data: {
                    id: id,
                    mqpathid: mqpathid
                },
                success: function (data) {
                    if (data.code > 0) {
                        alert("成功！");
                        window.location = window.location;
                    }
                    else {
                        alert(data.msg);
                    }
                }
            })
        }
    }
</script>
@section Scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @{Html.RegisterMvcPagerScriptResource();}
}
<div class="head">
    <div class="title">
        消费者管理 @Html.Raw(BusinessMQ.Web.Base.CommonHelper.Help(@"用于管理和查看当前队列的业务消费者和消费的分区。注意;删除消费者分区时,请先确保消费者未在线，且消费者的消息已被消费完毕，否则会导致该消费者的消费信息丢失。"))
    </div>
</div>
<div class="orderlist m10 myorder">
    @using (Html.BeginForm("index", "Consumer", FormMethod.Get, new RouteValueDictionary { { "id", "searchForm" } }))
    {
        <div class="item_list pt10">
            <div class="item_list">
                <ul>
                    <li>
                        <label>消费者业务标识</label><input type="text" name="consumerclientid" value="@ViewBag.consumerclientid" />
                         <label>分区编号</label><input type="text" name="partitionid" value="@ViewBag.partitionid" />
                         
                    </li>
                    <li>
                        <label>分区队列</label><input type="text" name="mqpathid" value="@ViewBag.mqpathid" />
                    </li>
                    <li class="search">
                        <input type="submit" class="btn1" value="搜索" accesskey="S" /></li>
                </ul>
            </div>
        </div>
    }
   @* <a href="@Url.Action("add", "Consumer")" class="btn1">新增</a>*@
    <div class="tab_cont">
        <div class="List">
            @Html.Partial("List",Model)
        </div>
    </div>
</div>

BusinessMQ.Web/Areas/ProConsum/Views/Consumer/List.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<BusinessMQ.Domain.Model.RegisterdConsumersModel>

<style>


        .divhide {
        overflow:hidden;
        height:200px;
        }
    .divopen {
    }
</style>
<table>
    <tbody><tr>
        <th style="">消费者业务标识[ID]</th>
        <th style="">分区编号(顺序)</th>
         <th style="">分区队列[ID]</th>
        <th style="">客户端</th>
        <th style="">最近消费时间</th>
        <th style="">最后消费消息ID</th>
        <th style="">消息消费情况</th>
        <th style="">创建时间</th>
        <th>操作</th>
    </tr>
        @foreach (var item in Model)
        {
         <tr style=" ">
            <td style="text-align:left;">@item.consumerclientmodel.client [@item.consumerclientmodel.id]</td>
            <td style="text-align:left;">@item.consumerpartitionmodel.partitionid (@item.consumerpartitionmodel.partitionindex)</td>
             <td style="text-align:left;"><a target="_blank" href="@Url.Action("Index", "Queue", new { Area="ProConsum",mqpathid=item.mqpathid })">@item.mqpath [@item.mqpathid]</a></td>
            <td style="text-align:left;">
                @{int state = 0;}
                @if (item.consumermodel.tempid  != 0)
                {
                    if (ViewBag.ServerDate - item.consumermodel.lastheartbeat < TimeSpan.FromSeconds(10))
                    {
                        <span style="color:green" title="会话:@item.consumermodel.tempid,客户端名称:@item.consumermodel.clientname,
                            创建时间:@BusinessMQ.Core.CommonHelper.ShowTime(ViewBag.ServerDate,item.consumermodel.createtime),
                            最后心跳:@BusinessMQ.Core.CommonHelper.ShowTime(ViewBag.ServerDate,item.consumermodel.lastheartbeat)">在线</span>
                        {state = 1;}
                    }
                    else
                    {
                        <span style="color:red" title="上次会话:@item.consumerpartitionmodel.lastconsumertempid,客户端名称:@item.consumermodel.clientname,
                            创建时间:@BusinessMQ.Core.CommonHelper.ShowTime(ViewBag.ServerDate, item.consumermodel.createtime),
                            最后心跳:@BusinessMQ.Core.CommonHelper.ShowTime(ViewBag.ServerDate, item.consumermodel.lastheartbeat)">中断</span>
                    {state = 2;}
                    }
                }
                else
                {
                      <span title="上次会话:@item.consumerpartitionmodel.lastconsumertempid">注销</span>
                    { state = 3; }
                }
                
            </td>
            <td style="text-align:left;">@BusinessMQ.Core.CommonHelper.ShowTime(ViewBag.ServerDate, item.consumerpartitionmodel.lastupdatetime)</td>
            <td style="text-align:left;"><a target="_blank" href="@Url.Action("Index", "Message", new { Area="Message",mqid=item.consumerpartitionmodel.lastmqid })">@item.consumerpartitionmodel.lastmqid</a></td>
             <td style="text-align:left;">(@item.nonMsgCount)未消费 (@item.msgCount)已消费</td>
              <td style="text-align:left;">@BusinessMQ.Core.CommonHelper.ShowTime(ViewBag.ServerDate, item.consumerpartitionmodel.createtime)</td>
            <td>
                <a href="@Url.Action("UpdateLastMqID", "Consumer", new { id = item.consumerpartitionmodel.id,mqpathid=item.mqpathid     })">重置消息ID</a>
                 @if (state==2)
                 {
                    <input type="button" value="清理相关中断" onclick="ClearNotOnLineByClientID('@item.consumerpartitionmodel.id    ','@item.mqpathid    ')">
                 }
                 @if (state==3)
                 {
                    <input type="button" value="删除" onclick="Delete('@item.consumerpartitionmodel.id    ','@item.mqpathid    ')">
                 }
            </td>
        </tr>
        }
</tbody></table>
<div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
    @Html.Pager(Model, new PagerOptions { PageIndexParameterName = "pageIndex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.TextBox, CssClass = "mvcPager" })
    @*@Ajax.Pager(Model, new PagerOptions { PageIndexParameterName = "pageindex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.DropDownList, ShowGoButton = false }, new MvcAjaxOptions { UpdateTargetId = "List", HttpMethod = "Post", DataFormId = "searchForm" }, new { @class = "pager_page" })*@
</div>

BusinessMQ.Web/Areas/ProConsum/Views/Consumer/UpdateLastMqID.cshtml
@{
    ViewBag.Title = "重置最后MQID";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    function sub() {
        if ($("#key").val() == "") {
            alert("请填写名称")
            return false;
        }
        if ($("#value").val() == "") {
            alert("请填写value");
            return false;
        }
        if ($("#remark").val() == "") {
            alert("请填写备注");
            return false;
        }
    }
</script>
<div class="head">
    <div class="title">
        重置最后消费消息ID
    </div>
</div>
<div>
    @using (Html.BeginForm("SaveUpdateLastMqID", "Consumer", FormMethod.Post, new { enctype = "multipart/form-data", @onsubmit = "return sub()" }))
    {
    <ul class="mydetail">
        <li>
            <input type="hidden" id="id" name="id" value="@ViewBag.id" /><input type="hidden" id="mqpathid" name="mqpathid" value="@ViewBag.mqpathid" />
        </li>
        <li>
            <label>最后消费的消息ID</label><input id="lastmqid" name="lastmqid" type="text" value="@ViewBag.lastmqid" />
        </li>
        <li>
            <input type="submit" class="btn1" value="提交" />@Html.ValidationMessage("Error")
        </li>
    </ul>
    }
</div>